# Generated by Django 2.2.1 on 2019-10-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191005_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReportAutofillTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cause_of_visit_template', models.TextField(blank=True, max_length=700)),
                ('checkup_template', models.TextField(blank=True, max_length=1200)),
                ('additional_checkup_template', models.TextField(blank=True, max_length=700)),
                ('prescription_template', models.TextField(blank=True, max_length=700)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'unique_together': {('doctor', 'name')},
            },
        ),
    ]
