# Generated by Django 2.2.1 on 2019-10-12 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profilereportautofilltemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilereportautofilltemplate',
            options={'verbose_name': 'Report autofill template', 'verbose_name_plural': 'Report autofill templates'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='districts',
            field=models.ManyToManyField(to='reports.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_col',
            field=models.CharField(max_length=9, unique=True, verbose_name='Num. col'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profilereportautofilltemplate',
            name='additional_checkup_template',
            field=models.TextField(blank=True, max_length=700, verbose_name='Additional checkup'),
        ),
        migrations.AlterField(
            model_name='profilereportautofilltemplate',
            name='cause_of_visit_template',
            field=models.TextField(blank=True, max_length=700, verbose_name='Cause of visit'),
        ),
        migrations.AlterField(
            model_name='profilereportautofilltemplate',
            name='checkup_template',
            field=models.TextField(blank=True, max_length=1200, verbose_name='Checkup'),
        ),
        migrations.AlterField(
            model_name='profilereportautofilltemplate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='profiles.Profile', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='profilereportautofilltemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profilereportautofilltemplate',
            name='prescription_template',
            field=models.TextField(blank=True, max_length=700, verbose_name='Prescription'),
        ),
    ]
