# Generated by Django 2.2.7 on 2020-02-19 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0008_remove_visittariff_price_doctor'),
        ('profiles', '0004_auto_20191012_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.District', verbose_name='District')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'District coverage',
                'verbose_name_plural': 'Districts coverage',
                'unique_together': {('user', 'district')},
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='districts',
        ),
        migrations.CreateModel(
            name='ProfileDistrictVisitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('profile_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileDistrict', verbose_name='District')),
                ('type_of_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.TypeOfVisit', verbose_name='Type of visit')),
            ],
            options={
                'verbose_name': 'Visit price for the doctor',
                'verbose_name_plural': 'Visit prices for the doctors',
                'unique_together': {('profile_district', 'type_of_visit')},
            },
        ),
    ]
