# Generated by Django 2.2.7 on 2020-02-24 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0008_remove_visittariff_price_doctor'),
        ('profiles', '0005_auto_20200219_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDistrictVisitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('type_of_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.TypeOfVisit', verbose_name='Type of visit')),
            ],
            options={
                'verbose_name': 'Visit price for the doctor',
                'verbose_name_plural': 'Visit prices for the doctors',
            },
        ),
        migrations.RenameModel(
            old_name='ProfileDistrict',
            new_name='UserDistrict',
        ),
        migrations.DeleteModel(
            name='ProfileDistrictVisitPrice',
        ),
        migrations.AddField(
            model_name='userdistrictvisitprice',
            name='user_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserDistrict', verbose_name='District'),
        ),
        migrations.AlterUniqueTogether(
            name='userdistrictvisitprice',
            unique_together={('user_district', 'type_of_visit')},
        ),
    ]
