# Generated by Django 3.0.4 on 2020-03-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20200309_1952'),
        ('profiles', '0006_auto_20200224_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistrict',
            name='cities',
            field=models.ManyToManyField(related_name='cities', to='reports.City', verbose_name='Cities'),
        ),
        migrations.AlterUniqueTogether(
            name='userdistrict',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userdistrict',
            name='district',
        ),
    ]
