# Generated by Django 3.0.4 on 2020-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_typeofvisit_short_name'),
        ('profiles', '0007_auto_20200310_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereportautofilltemplate',
            name='diagnosis',
            field=models.ManyToManyField(related_name='Autofill_template', to='reports.Disease', verbose_name='Diagnosis'),
        ),
    ]
