# Generated by Django 3.0.4 on 2020-03-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profilereportautofilltemplate_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilereportautofilltemplate',
            old_name='diagnosis',
            new_name='diagnosis_template',
        ),
    ]
