# Generated by Django 3.0.4 on 2020-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_userdistrict_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initials',
            field=models.CharField(blank=True, max_length=5, verbose_name='Initials'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_foreign_doctor',
            field=models.BooleanField(default=False, verbose_name='Is foreign doctor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_col',
            field=models.CharField(max_length=9, verbose_name='Num. col'),
        ),
    ]
