# Generated by Django 3.0.4 on 2020-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200318_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viber_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Viber id'),
        ),
    ]
