# Generated by Django 2.2.1 on 2019-06-22 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=40)),
                ('num_col', models.CharField(max_length=9, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=50)),
                ('company_ref_number', models.CharField(max_length=50)),
                ('patients_first_name', models.CharField(max_length=50)),
                ('patients_last_name', models.CharField(max_length=50)),
                ('patients_date_of_birth', models.DateField()),
                ('patients_policy_number', models.CharField(max_length=100)),
                ('patients_passport_number', models.CharField(max_length=100)),
                ('date_of_visit', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('cause', models.TextField(max_length=700)),
                ('checkup', models.TextField(max_length=1200)),
                ('additional_checkup', models.TextField(blank=True, max_length=500)),
                ('second_visit', models.BooleanField(default=False)),
                ('prescription', models.TextField(max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Company')),
                ('diagnosis', models.ManyToManyField(related_name='reports', to='reports.Disease')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='reports.Report')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.Service')),
            ],
        ),
    ]
