# Generated by Django 2.2.1 on 2019-10-05 18:55

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Country')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='reports.Country')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.District')),
                ('price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.PriceGroup')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
                'unique_together': {('district', 'price_group')},
            },
        ),
        migrations.CreateModel(
            name='TypeOfVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_second_visit', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Country')),
            ],
            options={
                'verbose_name': 'Type of visit',
                'verbose_name_plural': 'Types of visits',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=50)),
                ('company_ref_number', models.CharField(max_length=50)),
                ('patients_first_name', models.CharField(max_length=50)),
                ('patients_last_name', models.CharField(max_length=50)),
                ('patients_date_of_birth', models.DateField()),
                ('patients_policy_number', models.CharField(blank=True, max_length=100)),
                ('visit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_of_visit', models.DateTimeField()),
                ('detailed_location', models.CharField(blank=True, max_length=100)),
                ('cause_of_visit', models.TextField(max_length=700)),
                ('checkup', models.TextField(max_length=1200)),
                ('additional_checkup', models.TextField(blank=True, max_length=500)),
                ('prescription', models.TextField(max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('docx_download_link', models.CharField(blank=True, max_length=500)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Company')),
                ('diagnosis', models.ManyToManyField(related_name='reports', to='reports.Disease')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
                ('type_of_visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.TypeOfVisit')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'unique_together': {('patients_first_name', 'patients_last_name', 'ref_number')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Country')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='price_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.PriceGroup'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.District'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reports.models.get_image_path)),
                ('position', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='reports.Report')),
            ],
            options={
                'verbose_name': 'Additional Image',
                'verbose_name_plural': 'Additional Images',
            },
        ),
        migrations.CreateModel(
            name='VisitTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Tariff')),
                ('type_of_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.TypeOfVisit')),
            ],
            options={
                'verbose_name': 'Visit tariff',
                'verbose_name_plural': 'Visit tariffs',
                'unique_together': {('tariff', 'type_of_visit')},
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='reports.Report')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reports.Service')),
            ],
            options={
                'verbose_name': 'Service item',
                'verbose_name_plural': 'Service items',
                'unique_together': {('report', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(storage=reports.models.OverwriteStorage(), upload_to=reports.models.get_docxtemplate_path)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Country')),
            ],
            options={
                'verbose_name': 'Report template',
                'verbose_name_plural': 'Report templates',
                'unique_together': {('company', 'country')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'district')},
        ),
    ]
