# Generated by Django 2.2.1 on 2019-10-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='additional_checkup',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='prescription',
            field=models.TextField(max_length=700),
        ),
    ]
