# Generated by Django 2.2.7 on 2020-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200218_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='visit_price_doctor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Visit price for the doctor'),
            preserve_default=False,
        ),
    ]
