# Generated by Django 2.2.1 on 2019-07-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190713_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='cause',
            new_name='cause_of_visit',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patients_passport_number',
        ),
        migrations.RemoveField(
            model_name='report',
            name='second_visit',
        ),
        migrations.AddField(
            model_name='report',
            name='detailed_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='kind_of_visit',
            field=models.CharField(choices=[('D', 'Standard day visit'), ('N', 'Night visit'), ('f', 'Holiday visit'), ('F', 'Family visit'), ('S', 'Second visit')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='patients_policy_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_visit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('night_visit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('holiday_visit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('family_visit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('second_visit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.District')),
                ('price_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.PriceGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Country')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Region'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.District')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='price_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reports.PriceGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reports.City'),
            preserve_default=False,
        ),
    ]
