# Generated by Django 2.2.7 on 2020-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_visit_price_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_doctor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price for the doctor'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Service price'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service_price_doctor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Service price for the doctor'),
        ),
    ]
