# Generated by Django 2.2.1 on 2019-08-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20190811_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='reports.Country'),
        ),
        migrations.AddField(
            model_name='service',
            name='kind_of_visit',
            field=models.CharField(blank=True, choices=[('D', 'Standard day visit'), ('N', 'Night visit'), ('H', 'Holiday visit'), ('F', 'Family visit'), ('S', 'Second visit')], max_length=1, unique=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
