# Generated by Django 2.2.7 on 2020-02-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200218_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visittariff',
            name='price_doctor',
        ),
    ]
