# Generated by Django 2.2.1 on 2019-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20190811_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='kind_of_visit',
            field=models.CharField(blank=True, choices=[('D', 'Standard day visit'), ('N', 'Night visit'), ('H', 'Holiday visit'), ('F', 'Family visit'), ('S', 'Second visit')], max_length=1),
        ),
    ]
