# Generated by Django 2.2.7 on 2020-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_visittariff_price_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='visit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Visit price'),
        ),
        migrations.AlterField(
            model_name='report',
            name='visit_price_doctor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Visit price for the doctor'),
        ),
    ]
