# Generated by Django 2.2.1 on 2019-08-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190811_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='reports.Country'),
        ),
    ]
