# Generated by Django 2.2.7 on 2020-03-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200227_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='docx_download_link',
        ),
    ]
