# Generated by Django 2.2.1 on 2019-08-15 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190811_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reports.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='kind_of_visit',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='day_visit',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='family_visit',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='holiday_visit',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='night_visit',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='second_visit',
        ),
        migrations.AddField(
            model_name='disease',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reports.Country'),
        ),
        migrations.AlterField(
            model_name='report',
            name='kind_of_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Visit'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reports.Visit'),
            preserve_default=False,
        ),
    ]
