# Generated by Django 2.2.1 on 2019-08-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20190823_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='type_of_visit',
        ),
    ]
