# Generated by Django 2.2.1 on 2019-08-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_tariff_type_of_visit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitItem',
            new_name='VisitTariff',
        ),
    ]
