# Generated by Django 2.2.1 on 2019-09-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20190829_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='visit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
