# Generated by Django 3.0.4 on 2020-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20200313_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofvisit',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Short name'),
        ),
    ]
