# Generated by Django 2.2.1 on 2019-09-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_visit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='districts',
            field=models.ManyToManyField(to='reports.District'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
