# Generated by Django 2.2.1 on 2019-09-07 13:17

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20190907_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to=reports.models.get_image_path)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Country')),
            ],
        ),
    ]
