# Generated by Django 2.2.1 on 2019-09-08 15:52

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_reporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='template',
            field=models.FileField(upload_to=reports.models.get_docxtemplate_path),
        ),
        migrations.AlterField(
            model_name='typeofvisit',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Country'),
        ),
        migrations.AlterField(
            model_name='typeofvisit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('patients_first_name', 'patients_last_name', 'ref_number')},
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplate',
            unique_together={('company', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceitem',
            unique_together={('report', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('district', 'price_group')},
        ),
        migrations.AlterUniqueTogether(
            name='typeofvisit',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='visittariff',
            unique_together={('tariff', 'type_of_visit')},
        ),
    ]
