# Generated by Django 3.0.4 on 2020-03-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20200316_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('price_group',), 'verbose_name': 'Tariff', 'verbose_name_plural': 'Tariffs'},
        ),
    ]
