# Generated by Django 3.0.4 on 2020-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20200317_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='initials',
            field=models.CharField(blank=True, max_length=3, verbose_name='Initials'),
        ),
        migrations.AddField(
            model_name='typeofvisit',
            name='initial',
            field=models.CharField(blank=True, max_length=2, verbose_name='Initial'),
        ),
    ]
