# Generated by Django 2.2.1 on 2019-09-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20190908_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='kind_of_visit',
            new_name='type_of_visit',
        ),
    ]
