# Generated by Django 3.0.4 on 2020-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20200318_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ref_number',
            field=models.CharField(max_length=6, verbose_name='Ref. number'),
        ),
    ]
