# Generated by Django 2.2.1 on 2019-09-17 19:36

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20190912_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='template',
            field=models.FileField(storage=reports.models.OverwriteStorage(), upload_to=reports.models.get_docxtemplate_path),
        ),
    ]
