# Generated by Django 3.0.4 on 2020-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20200318_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='cost_doctor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cost doctor'),
        ),
    ]
