# Generated by Django 3.0.4 on 2020-03-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20200319_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('can_download_excel', 'Can download excel'),), 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
