# Generated by Django 2.2.1 on 2019-09-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20190925_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofvisit',
            name='is_second_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='typeofvisit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
