# Generated by Django 3.0.4 on 2020-03-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200318_1750'),
        ('reports', '0021_auto_20200319_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('message', models.TextField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Company', verbose_name='Company')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Report request')),
                ('report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Report')),
            ],
        ),
    ]
