# Generated by Django 3.0.4 on 2020-03-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_reportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Report'),
        ),
    ]
