# Generated by Django 3.0.4 on 2020-03-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200318_1750'),
        ('reports', '0023_auto_20200321_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Report request'),
        ),
    ]
