# Generated by Django 3.0.4 on 2020-03-26 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200318_1750'),
        ('reports', '0026_auto_20200326_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='date_time',
            field=models.DateTimeField(verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Message'),
        ),
    ]
