# Generated by Django 3.0.4 on 2020-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20200329_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='ref_number',
            field=models.IntegerField(verbose_name='Ref. number'),
        ),
    ]
