# Generated by Django 3.0.4 on 2020-03-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_auto_20200329_1914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportrequest',
            unique_together={('ref_number', 'company')},
        ),
    ]
