# Generated by Django 3.0.4 on 2020-03-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_auto_20200330_0133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportrequest',
            unique_together=set(),
        ),
    ]
