# Generated by Django 3.0.4 on 2020-03-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_auto_20200330_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='reports.ReportRequest'),
        ),
    ]
