# Generated by Django 3.0.4 on 2020-03-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_auto_20200330_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor',
        ),
    ]
