# Generated by Django 3.0.4 on 2020-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_remove_report_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalimage',
            name='expand',
            field=models.BooleanField(default=False, verbose_name='Expand'),
        ),
    ]
