# Generated by Django 3.0.4 on 2020-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_additionalimage_expand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Is accepted'), ('cancelled_by_company', 'Cancelled by company'), ('wrong_data', 'Wrong request data'), ('failed', 'The visit did not take place')], default='accepted', max_length=20, verbose_name='Status'),
        ),
    ]
