# Generated by Django 3.0.4 on 2020-04-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_auto_20200409_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_city_state',
            field=models.BooleanField(default=False, verbose_name='City-state'),
        ),
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='reports.Country', verbose_name='Country'),
        ),
    ]
