# Generated by Django 3.0.4 on 2020-04-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_auto_20200409_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportrequest',
            options={'verbose_name': 'Report request', 'verbose_name_plural': 'Report requests'},
        ),
    ]
