# Generated by Django 3.0.4 on 2020-04-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0041_auto_20200413_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='ref_number',
            field=models.PositiveIntegerField(verbose_name='Ref. number'),
        ),
    ]
