# Generated by Django 3.0.4 on 2020-04-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0042_auto_20200426_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='reports.ReportRequest', verbose_name='Report request'),
        ),
    ]
